### ISSUE TITLE
Shorter pages sometimes rubberband when scrolling

### ISSUE THREAD

**Issue by colindean** [metamesh/metamesh.org#9]
https://gfycat.com/PopularSlimFinwhale

![in action](https://giant.gfycat.com/PopularSlimFinwhale.gif)

**Comment by starthal** [comment]
I'm experiencing this, but only on the **Projects** page. Also only when text zoom level is 3 smaller than default. Shrinking the window vertically also eliminates the issue.

Firefox 38.0 on Ubuntu 14.04.
